spring:
  # 关闭thymleaf的缓存
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 232521
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5